### ISSUE TITLE
String literal found in code section

### ISSUE THREAD

**Issue by munic-sjj** [crskycode/EntisGLS_Tools#10]
Hello, I tried all the tools, and found that starting from v1.6, the CSXToolPlus -a script.csx command can extract text, but it outputs a message like WARNING: 007AE6E9 String literal found in code section!. In this case, the CSXToolPlus -b script.csx command generates a script.new.csx file that is no different from the original script.csx, even though I have modified the script.txt.I'd like to ask if you're interested in making the CSXToolPlus -b script.csx command work. Here is the file:[script.zip](https://github.com/user-attachments/files/17659999/script.zip)
![C__Windows_system32_cmd exe 2024_11_7 18_17_45](https://github.com/user-attachments/assets/11dfb408-5f93-44ea-9d66-ac8ad93fa872)

**Comment by crskycode** [comment]
https://github.com/crskycode/EntisGLS_Tools/releases/tag/v1.9
