### ISSUE TITLE
help

### ISSUE THREAD

**Issue by fushi002** [crskycode/EntisGLS_Tools#2]
![image](https://github.com/crskycode/EntisGLS_Tools/assets/88200209/6c41a335-5374-42f9-88b2-448cc4010985)

https://vndb.org/v11487
The script file for the game linked above.
[script.zip](https://github.com/crskycode/EntisGLS_Tools/files/14387577/script.zip)

It's not working properly

**Comment by crskycode** [comment]
Try [CSXToolPlus](https://github.com/crskycode/EntisGLS_Tools/releases/tag/v1.4)

**Comment by fushi002** [comment]
Thanks!
