### ISSUE TITLE
Hello, I have encountered some problems while using your development of EntisGLS_Tools.

### ISSUE THREAD

**Issue by dxx137** [crskycode/EntisGLS_Tools#3]
The following problem occurred while exporting the text of game 恋色マリアージュ
This is a problem that occurred while using CSXToolPlus v1.0_win-64
![QQ截图20240309014907](https://github.com/crskycode/EntisGLS_Tools/assets/140311615/0e0ba84b-3c0a-4a1e-8704-3aa70dd0913f)
This is a problem that occurred with the use of CSXTool_v1.3_win-64.
![QQ截图20240309015045](https://github.com/crskycode/EntisGLS_Tools/assets/140311615/f23c8a07-b83a-41ba-ba84-4a168a89eee7)
这是script.csx
[script.zip](https://github.com/crskycode/EntisGLS_Tools/files/14541565/script.zip)
If possible, please handle it, thank you.

**Comment by crskycode** [comment]
Try [v1.1](https://github.com/crskycode/EntisGLS_Tools/releases/tag/v1.5) 
```
CSXToolPlus -a script.csx -v2
CSXToolPlus -b script.csx -v2
```

**Comment by dxx137** [comment]
可以了，谢谢（Okay, thank you）
