### ISSUE TITLE
Thank you very much for your last reply, but I have encountered a problem again with extracting another game from the same company this time.

### ISSUE THREAD

**Issue by dxx137** [crskycode/EntisGLS_Tools#5]
This game is らぶ２Ｑｕａｄ,the situation with this game is a bit different from before.
If using CSXToolPlus, it appears to run normally but the exported txt file is blank.
![QQ截图20240316221451](https://github.com/crskycode/EntisGLS_Tools/assets/140311615/e98f2ebe-af0b-4da8-ac74-eb5991029fdd)
![QQ截图20240316221853](https://github.com/crskycode/EntisGLS_Tools/assets/140311615/345b5c14-9c05-4bcd-8bae-f9d02232541d)
If CSXTool_v1.3 is used, the following situation will occur.
![QQ截图20240316220821](https://github.com/crskycode/EntisGLS_Tools/assets/140311615/65f4131d-37aa-412a-8ec6-2b5841448994)
This is the text file of the game.
[script.zip](https://github.com/crskycode/EntisGLS_Tools/files/14624246/script.zip)

**Comment by crskycode** [comment]
Try [v1.2](https://github.com/crskycode/EntisGLS_Tools/releases/tag/v1.6)

**Comment by dxx137** [comment]
Succeeded, thank you
