### ISSUE TITLE
Found invalid data while decoding

### ISSUE THREAD

**Issue by fgpzen** [crskycode/EntisGLS_Tools#8]
作者你好，看到你Bio用的中文我就用中文了哈。
使用了最新的v1.6 release包，CSXTool -a /-e  CSXToolPlus -a /-a -v2 我都试过了，无法解析这个脚本
CSX 用  GARbro 解的
![image](https://github.com/crskycode/EntisGLS_Tools/assets/14107012/fbfc2b76-d183-4600-9015-92cb64e8504e)

感谢作者
这是文件[script.zip](https://github.com/user-attachments/files/15747141/script.zip)

**Comment by crskycode** [comment]
The script file is not extracted correctly, so the data in that file cannot be parsed.

**Comment by fgpzen** [comment]
嗯我发现了。这个dat是加密的，拉了你的GARbro代码看了下，GARbro没有正确提取出csx，应该是已经正确获取了 IDR_COTOMI，但不知道为什么没能正确提取csx出来。

**Comment by fgpzen** [comment]
> The script file is not extracted correctly, so the data in that file cannot be parsed.

我已经解密并正确提取了，用010Editor可以看到日文文本，但还是解析失败 （CSXTool -a /-e CSXToolPlus -a /-a -v2）都试过了。
[script.zip](https://github.com/user-attachments/files/15751488/script.zip)

**Comment by crskycode** [comment]
Use CSXTool 1.4 run `CSXTool -a script.csx`

**Comment by fgpzen** [comment]
我确认一下 用1.4 老包，而不是你刚更新的v1.7 ？

**Comment by fgpzen** [comment]
哦我明白了，新包是 CSXTool v1.4

**Comment by fgpzen** [comment]
试了下确实可以了，感谢😄
