### ISSUE TITLE
EndOfStreamException: Unable to read beyond the end of the stream.

### ISSUE THREAD

**Issue by fgpzen** [crskycode/EntisGLS_Tools#9]
作者你好，我又遇到问题了😂，请教一下。
使用了最新的v1.7 tag的 release包，CSXTool -a /-e CSXToolPlus -a /-a -v2 我都试过了，都无法解析这几个脚本。
CSX 用 GARbro 解的，已确认都是正常提取了脚本。
![image](https://github.com/crskycode/EntisGLS_Tools/assets/14107012/f86a9890-3f80-4667-bdcf-210a192db2f1)
![image](https://github.com/crskycode/EntisGLS_Tools/assets/14107012/7011d114-5470-451c-a235-98ed77963f66)

感谢作者，无法解析的脚本，有5个：[script.zip](https://github.com/user-attachments/files/15846188/script.zip)

**Comment by crskycode** [comment]
There is some junk data at the end of the script file you extracted, it's not a defect of the script tool, but I improved the tool to make it compatible with those scripts.

**Comment by fgpzen** [comment]
明白了，非常感谢。看来是脚本格式的问题😂，多谢你的改进让我可以翻译这几部作品😊。
